apiVersion: apps/v1
kind: Deployment
metadata:
  name: etf-backend
spec:
  replicas: {{ .Values.backend.deployment.replicas }}
  selector:
    matchLabels:
      app: etf-backend
  template:
    metadata:
      labels:
        app: etf-backend
    spec:
      initContainers:
        - name: init-myservice
          image: mysql:5
          command: 'sh'
          args: ['-c', 'until mysqladmin --host=etf-backend-mysql.{{ .Release.Namespace }}.svc.cluster.local --user={{ .Values.backend.mysql.config.user }} --password={{ .Values.backend.mysql.config.password }} status; do echo waiting for MySQL; sleep 2; done;']
      containers:
        - image: micalgenus/etf:backend-{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: etf-backend
          env:
            - name: MYSQL_HOST
              value: etf-backend-mysql.{{ .Release.Namespace }}.svc.cluster.local
            - name: MYSQL_PORT
              value: {{ 3306 | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.backend.mysql.config.db }}
            - name: MYSQL_USER
              value: {{ .Values.backend.mysql.config.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.backend.mysql.config.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.backend.mysql.config.rootPassword }}

---
apiVersion: v1
kind: Service
metadata:
  name: etf-backend
spec:
  selector:
    app: etf-backend
  ports:
    - name: tomcat
      port: 8080
      targetPort: 8080

---
{{- if .Values.backend.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: etf-backend
  annotations:
  {{- range $key, $value := .Values.backend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: etf-backend
              servicePort: tomcat
  {{- if .Values.backend.ingress.tls.enabled }}
  tls:
    - hosts:
        # Change this to your own hostname
        - {{ .Values.backend.ingress.host }}
  {{- end }}
{{- end }}    IizuYX7fivTKqcAvjuRporc+PNv1psOqlrN1VwEpvTM9Xn+tpxN09FS1LFtkfrIWhYrH47Idf8Sq
    lEhh3RmlCn4/X6DXoWnATMyc6hsUSWuvCZBz/963i6tpkjP/QJB+Gw7AwQOIEchFoSOO85SsDrox
    ZTZqWb+q4Hydbsxe/wiXqOK7kZHH6bpie82X9LvmCQGpijNbinnOsWtK2C8ChvSV8SyXkT39hM9o
    wNNwU4h/EBFZZdpsNRbY0P+Jb88YGi4+7rDp5ceTiXPlcf+QaA5hULiK0hAWOeweqAPI3nS0VKK1
    umzWJIAAYNjALIC/VT0wsVdSSsi4C46rHgK782p5vQxj15vb3KKV4m/RH2hhGSQLRgBE2KIHHyfH
    5xT073AI8lh4TwfD+l8WeOg9UZToMD4wITAJBgUrDgMCGgUABBQLyXYe1mLWIDzPuQwQt+3NujyD
    mgQURhxHd88v7s+ZBqvmDs7wAaau2TsCAwGGoA==
