backend:
  deployment:
    replicas: 1
  mysql:
    config:
      db: etf
      user: etf
      password: password
      rootPassword: rootPassword
  ingress:
    enabled: false
    annotations:
    host: backend.etf.com
    tls:
      enabled: false
