backend:
  deployment:
    replicas: 1
  mysql:
    config:
      db: etf
      user: etf
      password: password
      rootPassword: rootPassword
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
      certmanager.k8s.io/issuer: "letsencrypt-prod"
      certmanager.k8s.io/acme-challenge-type: http01
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    host: backend.etf.com
    tls:
      enabled: false

